### ISSUE TITLE
difficult to use

### ISSUE THREAD

**Issue by towry** [imNel/monorepo.nvim#5]
1. don't know how to add project, it keep saying not in a project if I run toggle_project.
2. prompt_project('add') doesn't work as expected, after use it to add `./apps/project-a`, and switch to it, error happened, file not exists `/Users/x/work/monorepo-a//./apps/project-a` not exists.

**Comment by imNel** [comment]
Hey thanks for leaving some feedback, I'll try to answer as best as possible :)

1. You can use `add_project()` or `prompt_project("add")` to add a project. Remember that the "main" project is the one you start `nvim` in. You can run `:pwd` to see what that directory is.

2. Since `./apps/project-a` and `apps/project-a` would be doing the same thing here, ./ doesnt work (although I'm looking at fixing it now)

Let me know if you have any other questions :)

**Comment by imNel** [comment]
fixed no. 2 in 64bd824
